### ISSUE TITLE
Unable to establish database connection.

### ISSUE THREAD

**Issue by TroyWitthoeft** [ungleng/SimpleAjaxPagedListAndSearchMVC5#1]
Downloaded source from GitHub.  Double-clicked solution.  VS 2013. Built Solution.  Build Successful.  Launched Solution. Got server error after a 30 second timeout.    

> A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. The specified LocalDB instance does not exist.

Perhaps target .sln example for AdventureWorks, or find another way to Seed the database?

**Comment by ungleng** [comment]
Look like you don have LocalDB install. Anyway you  could change the connection string in Web.config to suit your environment

**Comment by ungleng** [comment]
After checkout this project to rebuild again, I have find out that I have remove my connection string for private reason in last check in. so you can simply add your local connection string back in web.config. it would work properly. 

``` xml
<connectionStrings>
      <add name="defaultConnection" connectionString=" Server=;Database=SimpleAjax-Db;User Id=;Password=;" providerName="System.Data.SqlClient" />
</connectionStrings>
```
